### ISSUE TITLE
Can't import "vlc"

### ISSUE THREAD

**Issue by Falcn8** [acatiadroid/music-player#1]
When I run `python3 mp.py`...

```
Traceback (most recent call last):
  File "/Users/XXX/Documents/Programming/stuff/music-player/mp.py", line 4, in <module>
    import vlc
  File "/opt/homebrew/lib/python3.9/site-packages/vlc.py", line 210, in <module>
    dll, plugin_path  = find_lib()
  File "/opt/homebrew/lib/python3.9/site-packages/vlc.py", line 191, in find_lib
    ctypes.CDLL('libvlccore.dylib')
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libvlccore.dylib, 0x0006): tried: '/opt/homebrew/lib/libvlccore.dylib' (no such file), '/opt/homebrew/lib/libvlccore.dylib' (no such file), 'libvlccore.dylib' (no such file), '/usr/local/lib/libvlccore.dylib' (no such file), '/usr/lib/libvlccore.dylib' (no such file), '/Users/XXX/Documents/Programming/stuff/music-player/libvlccore.dylib' (no such file), '/usr/local/lib/libvlccore.dylib' (no such file), '/usr/lib/libvlccore.dylib' (no such file)
```

**Comment by acatiadroid** [comment]
Should be fixed

**Comment by acatiadroid** [comment]
VLC no longer used now.
